# Generated by Django 5.2.8 on 2026-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', help_text='Password will be automatically hashed', max_length=255),
        ),
    ]
