# Generated by Django 5.2.8 on 2026-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_doctor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
