# Generated by Django 6.0.2 on 2026-03-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_hospitaladmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
