# Generated by Django 6.0.2 on 2026-03-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_department_hospital_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='directory.hospital'),
        ),
    ]
